### ISSUE TITLE
2/3 Lab 1 Progress Report

### ISSUE THREAD

**Issue by shadow12490** [shadow12490/msbx5500-spring-2020#2]
@deargle 

Completed sections down to the AWS/Colab/Azure section.
Been working through Kaggle, have at least read the first three topics and completed the exercises for the intro to ML. 
Have an EXTREMELY basic github page set up.

Need to do the Amazon/Colab/Azure tutorials still
Need to fill in definitions in the "Gain Knowledge section"

**Comment by shadow12490** [comment]
I also took both midterms and did really bad on number 1 (6.67/22) and slightly less bad on number 2 (12/24)

**Comment by deargle** [comment]
Thanks for the progress report. I'm going to open separate issues for the different lab deliverables. I think it will be easier to track that way, hopefully.
